# Generated by Django 4.1.7 on 2023-04-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menuitem_named_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название меню')),
            ],
            options={
                'verbose_name': 'Название меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['menu_title'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='title',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item',
            field=models.CharField(max_length=255, verbose_name='Название пункта'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='Надпункт меню'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu', verbose_name='Меню'),
            preserve_default=False,
        ),
    ]
