# Generated by Django 4.1.7 on 2023-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_alter_menuitem_options_remove_menuitem_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item',
            field=models.CharField(max_length=255, verbose_name='Название пункта меню'),
        ),
    ]
