# Generated by Django 4.1.7 on 2023-04-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menuitem_options_menuitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень вложенности'),
        ),
    ]
